// generated by koharu-protocol; do not edit

import { request } from './transport'

export const commands = {
  getStartup: () => request<StartupState>('get_startup'),
  getProject: () => request<ProjectInfo | null>('get_project'),
  getPages: () => request<PageSummary[]>('get_pages'),
  getPage: () => request<Page | null>('get_page'),
  listProjects: () => request<ProjectSummary[]>('list_projects'),
  createProject: (name: string) => request<null>('create_project', { name }),
  openProject: (name: string) => request<null>('open_project', { name }),
  deleteProject: (name: string) => request<null>('delete_project', { name }),
  closeProject: () => request<null>('close_project'),
  importPages: (source: PageImportSource) => request<null>('import_pages', { source }),
  selectPage: (page: EntityId) => request<null>('select_page', { page }),
  renamePage: (page: EntityId, label: string) => request<null>('rename_page', { page, label }),
  deletePages: (pages: EntityId[]) => request<null>('delete_pages', { pages }),
  movePage: (page: EntityId, index: number) => request<null>('move_page', { page, index }),
  setSourceText: (layer: EntityId, text: string) => request<null>('set_source_text', { layer, text }),
  setTranslation: (layer: EntityId, text: string | null) => request<null>('set_translation', { layer, text }),
  setTypography: (updates: TypographyUpdate[]) => request<null>('set_typography', { updates }),
  setGeometry: (updates: GeometryUpdate[]) => request<null>('set_geometry', { updates }),
  setVisibility: (layers: EntityId[], visible: boolean | null, opacity: number | null) => request<null>('set_visibility', { layers, visible, opacity }),
  deleteLayers: (layers: EntityId[]) => request<null>('delete_layers', { layers }),
  moveLayer: (layer: EntityId, parent: EntityId, index: number) => request<Page>('move_layer', { layer, parent, index }),
  undo: () => request<null>('undo'),
  redo: () => request<null>('redo'),
  process: (scope: Scope, operation: Operation) => request<JobId>('process', { scope, operation }),
  stopJob: (job: JobId) => request<null>('stop_job', { job }),
  exportPages: (pages: EntityId[], format: ExportFormat) => request<null>('export_pages', { pages, format }),
  getThumbnail: (page: EntityId) => request<ArrayBuffer>('get_thumbnail', { page }),
  getFonts: () => request<FontFamily[]>('get_fonts'),
  getFontPreview: (familyName: string) => request<ArrayBuffer>('get_font_preview', { familyName }),
  savePreferences: (pipeline: PipelineConfig, providers: ProviderPreferences, typesetting: TypesettingConfig) => request<Preferences>('save_preferences', { pipeline, providers, typesetting }),
  getPreferences: () => request<Preferences>('get_preferences'),
  getTranslationModels: () => request<Model[]>('get_translation_models'),
  setZoom: (zoom: number) => request<null>('set_zoom', { zoom }),
  setCanvasView: (zoom: number, translation: [number, number]) => request<null>('set_canvas_view', { zoom, translation }),
  fitCanvas: () => request<null>('fit_canvas'),
  addPointText: (point: Point) => request<LayerCommit>('add_point_text', { point }),
  addTextBox: (frame: Frame) => request<LayerCommit>('add_text_box', { frame }),
  beginPaint: (layer: EntityId | null, point: Point, brush: PaintBrush) => request<null>('begin_paint', { layer, point, brush }),
  extendPaint: (points: Point[]) => request<null>('extend_paint', { points }),
  finishPaint: () => request<LayerCommit>('finish_paint'),
  cancelPaint: () => request<null>('cancel_paint'),
  beginErase: (layer: EntityId, point: Point, diameter: number) => request<null>('begin_erase', { layer, point, diameter }),
  extendErase: (points: Point[]) => request<null>('extend_erase', { points }),
  finishErase: () => request<LayerCommit>('finish_erase'),
  cancelErase: () => request<null>('cancel_erase'),
  beginTransform: (elements: TransformFrame[]) => request<null>('begin_transform', { elements }),
  updateTransform: (frame: number, elements: TransformFrame[]) => request<null>('update_transform', { frame, elements }),
  previewOpacity: (element: EntityId, opacity: number | null) => request<null>('preview_opacity', { element, opacity }),
  finishTransform: () => request<Revision | null>('finish_transform'),
  cancelTransform: () => request<null>('cancel_transform'),
  beginInpaint: (point: Point, diameter: number) => request<null>('begin_inpaint', { point, diameter }),
  extendInpaint: (points: Point[]) => request<null>('extend_inpaint', { points }),
  finishInpaint: () => request<JobId | null>('finish_inpaint'),
  cancelInpaint: () => request<null>('cancel_inpaint'),
  sampleColor: (point: Point) => request<[number, number, number, number]>('sample_color', { point }),
  setViewport: (x: number, y: number, width: number, height: number, dpr: number, background: [number, number, number]) => request<null>('set_viewport', { x, y, width, height, dpr, background }),
  getAgentStatus: () => request<AgentStatus>('get_agent_status'),
  loginAgent: () => request<AgentStatus>('login_agent'),
  logoutAgent: () => request<AgentStatus>('logout_agent'),
  saveAgentConfig: (config: Config) => request<Config>('save_agent_config', { config }),
  runAgent: (prompt: string) => request<RunId>('run_agent', { prompt }),
  cancelAgent: (run: RunId) => request<null>('cancel_agent', { run }),
  checkUpdate: () => request<UpdateInfo | null>('check_update'),
  installUpdate: (version: string) => request<null>('install_update', { version }),
} as const

// This file has been generated by Specta. Do not edit this file manually.
export type Account = {
	id: string,
	email: string | null,
	plan: string | null,
};

export type AgentStatus = {
	account: Account | null,
	models: CodexModel[],
	config: Config,
	running: RunId | null,
};

export type AnalysisRegion = {
	id: EntityId,
	parent: EntityId | null,
	geometry: Geometry,
	kind: string,
	label: string | null,
};

export type AppError = {
	code: AppErrorCode,
	message: string,
};

export type AppErrorCode = "invalid_request" | "not_ready" | "no_project" | "conflict" | "not_found" | "cancelled" | "unavailable" | "internal";

export type AppEvent = { type: "startup_ready"; startup: StartupState } | { type: "startup_failed"; error: AppError } | { type: "canvas"; state: CanvasState } | { type: "job"; job: Job } | { type: "download"; download: Download } | { type: "resources"; resources: ModelResources } | { type: "project"; project: ProjectInfo | null } | { type: "agent_login"; event: LoginEvent } | { type: "agent_run"; event: Event } | { type: "window_state"; state: WindowState } | { type: "update_progress"; progress: UpdateProgress };

export type AtlasCloudConfig = Record<string, never>;

export type BinaryPayload = {
	attachment: string,
};

export type Bounds = {
	x: number,
	y: number,
	width: number,
	height: number,
};

export type CaiyunConfig = Record<string, never>;

export type CanvasState = {
	zoom: number,
	translation: [number, number],
	fitted: boolean,
	element_frames: TransformFrame[],
};

export type ClaudeConfig = Record<string, never>;

export type CodexModel = {
	id: string,
	name: string,
	reasoning: Reasoning[],
};

export type Command = { command: "get_startup" } | { command: "get_project" } | { command: "get_pages" } | { command: "get_page" } | { command: "list_projects" } | { command: "create_project"; payload: {
	name: string,
} } | { command: "open_project"; payload: {
	name: string,
} } | { command: "delete_project"; payload: {
	name: string,
} } | { command: "close_project" } | { command: "import_pages"; payload: {
	source: PageImportSource,
} } | { command: "select_page"; payload: {
	page: EntityId,
} } | { command: "rename_page"; payload: {
	page: EntityId,
	label: string,
} } | { command: "delete_pages"; payload: {
	pages: EntityId[],
} } | { command: "move_page"; payload: {
	page: EntityId,
	index: number,
} } | { command: "set_source_text"; payload: {
	layer: EntityId,
	text: string,
} } | { command: "set_translation"; payload: {
	layer: EntityId,
	text: string | null,
} } | { command: "set_typography"; payload: {
	updates: TypographyUpdate[],
} } | { command: "set_geometry"; payload: {
	updates: GeometryUpdate[],
} } | { command: "set_visibility"; payload: {
	layers: EntityId[],
	visible: boolean | null,
	opacity: number | null,
} } | { command: "delete_layers"; payload: {
	layers: EntityId[],
} } | { command: "move_layer"; payload: {
	layer: EntityId,
	parent: EntityId,
	index: number,
} } | { command: "undo" } | { command: "redo" } | { command: "process"; payload: {
	scope: Scope,
	operation: Operation,
} } | { command: "stop_job"; payload: {
	job: JobId,
} } | { command: "export_pages"; payload: {
	pages: EntityId[],
	format: ExportFormat,
} } | { command: "get_thumbnail"; payload: {
	page: EntityId,
} } | { command: "get_fonts" } | { command: "get_font_preview"; payload: {
	familyName: string,
} } | { command: "save_preferences"; payload: {
	pipeline: PipelineConfig,
	providers: ProviderPreferences,
	typesetting: TypesettingConfig,
} } | { command: "get_preferences" } | { command: "get_translation_models" } | { command: "set_zoom"; payload: {
	zoom: number,
} } | { command: "set_canvas_view"; payload: {
	zoom: number,
	translation: [number, number],
} } | { command: "fit_canvas" } | { command: "add_point_text"; payload: {
	point: Point,
} } | { command: "add_text_box"; payload: {
	frame: Frame,
} } | { command: "begin_paint"; payload: {
	layer: EntityId | null,
	point: Point,
	brush: PaintBrush,
} } | { command: "extend_paint"; payload: {
	points: Point[],
} } | { command: "finish_paint" } | { command: "cancel_paint" } | { command: "begin_erase"; payload: {
	layer: EntityId,
	point: Point,
	diameter: number,
} } | { command: "extend_erase"; payload: {
	points: Point[],
} } | { command: "finish_erase" } | { command: "cancel_erase" } | { command: "begin_transform"; payload: {
	elements: TransformFrame[],
} } | { command: "update_transform"; payload: {
	frame: number,
	elements: TransformFrame[],
} } | { command: "preview_opacity"; payload: {
	element: EntityId,
	opacity: number | null,
} } | { command: "finish_transform" } | { command: "cancel_transform" } | { command: "begin_inpaint"; payload: {
	point: Point,
	diameter: number,
} } | { command: "extend_inpaint"; payload: {
	points: Point[],
} } | { command: "finish_inpaint" } | { command: "cancel_inpaint" } | { command: "sample_color"; payload: {
	point: Point,
} } | { command: "set_viewport"; payload: {
	x: number,
	y: number,
	width: number,
	height: number,
	dpr: number,
	background: [number, number, number],
} } | { command: "get_agent_status" } | { command: "login_agent" } | { command: "logout_agent" } | { command: "save_agent_config"; payload: {
	config: Config,
} } | { command: "run_agent"; payload: {
	prompt: string,
} } | { command: "cancel_agent"; payload: {
	run: RunId,
} } | { command: "window_minimize" } | { command: "window_toggle_maximize" } | { command: "window_close" } | { command: "window_begin_drag" } | { command: "open_external"; payload: {
	url: string,
} } | { command: "get_version" } | { command: "check_update" } | { command: "install_update"; payload: {
	version: string,
} };

export type CommandResult = null | StartupState | ProjectInfo | null | ProjectSummary[] | PageSummary[] | Page | null | Page | CanvasState | LayerCommit | Revision | null | JobId | JobId | null | BinaryPayload | FontFamily[] | Preferences | Model[] | [number, number, number, number] | AgentStatus | Config | RunId | WindowState | string | UpdateInfo | null;

export type Config = {
	model: string | null,
	reasoning: Reasoning,
};

export type CredentialInput = {
	configured: boolean,
	value: string | null,
	clear: boolean,
};

export type DeepLConfig = {
	base_url?: string | null,
};

export type DeepSeekConfig = Record<string, never>;

export type DetectionModel = {
	model: "koharu-layout-rfdetr-seg-2xl",
} & KoharuLayoutRFDetrSeg2XLConfig;

export type DeviceResources = {
	name: string,
	selected: boolean,
	memory_budget: number | null,
	memory_used: number | null,
	utilization: number | null,
};

export type Download = {
	id: number,
	state: DownloadState,
	name: string | null,
	completed: number,
	total: number,
	error: string | null,
};

export type DownloadState = "running" | "finished" | "failed";

export type EntityId = string;

export type Event = { type: "started"; run: RunId } | { type: "text_delta"; run: RunId; delta: string } | { type: "reasoning_delta"; run: RunId; delta: string } | { type: "tool_started"; run: RunId; call_id: string; name: string } | { type: "tool_finished"; run: RunId; call_id: string; name: string; changed: boolean; output: string } | { type: "completed"; run: RunId; message: string } | { type: "failed"; run: RunId; message: string } | { type: "cancelled"; run: RunId };

export type ExportFormat = "png" | "psd";

export type Flux2KleinConfig = {
	prompt?: string,
};

export type Flux1FillDevConfig = {
	prompt?: string,
};

export type FontFace = {
	postscript_name: string,
	weight: number,
	weight_range: FontRange | null,
	style: FontStyle,
};

export type FontFamily = {
	name: string,
	metadata: FontMetadata,
	sources: FontSource[],
	faces: FontFace[],
};

export type FontMetadata = {
	primary_script: string | null,
	scripts: string[],
	languages: string[],
	category: string | null,
	classifications: string[],
	use_cases: string[],
};

export type FontRange = {
	minimum: number,
	maximum: number,
};

export type FontSource = "system" | "bundled";

export type FontStyle = "normal" | "italic" | "oblique";

export type Frame = {
	x: number,
	y: number,
	width: number,
	height: number,
	angle_degrees: number,
};

export type GeminiConfig = Record<string, never>;

export type GenerationConfig = {
	temperature?: number | null,
	top_k?: number | null,
	top_p?: number | null,
	min_p?: number | null,
	max_tokens?: number | null,
	repeat_penalty?: number | null,
	frequency_penalty?: number | null,
	presence_penalty?: number | null,
	thinking?: boolean,
};

export type Geometry = {
	points: Point[],
};

export type GeometryUpdate = {
	layer: EntityId,
	points: Point[] | null,
};

export type GoogleCloudConfig = Record<string, never>;

export type GroupRole = "text";

export type InpaintingModel = { model: "lama" } | { model: "aot-inpainting" } | {
	model: "flux2-klein",
} & Flux2KleinConfig | {
	model: "flux1-fill-dev",
} & Flux1FillDevConfig | {
	model: "rorem-mixed",
} & RoremMixedConfig;

export type Job = {
	id: JobId,
	state: JobState,
	completed: number,
	total: number,
	page: EntityId | null,
	stage: Stage | null,
	model: string | null,
	error: string | null,
};

export type JobId = string;

export type JobState = "running" | "finished" | "failed" | "stopped";

export type KoharuLayoutRFDetrSeg2XLConfig = {
	text_threshold?: number | null,
	bubble_threshold?: number | null,
	panel_threshold?: number | null,
};

export type LanguageChoice = {
	tag: string,
	name: string,
};

export type Layer = { type: "group"; id: EntityId; parent: EntityId | null; visibility: LayerVisibility; name: string; role: GroupRole | null } | { type: "text"; id: EntityId; parent: EntityId | null; geometry: Geometry | null; visibility: LayerVisibility; content: TextContent; typography: Typography | null; layout: TextLayoutKind; automatic_region: EntityId | null } | { type: "raster"; id: EntityId; parent: EntityId | null; visibility: LayerVisibility; image: string | null; name: string; kind: RasterLayerKind } | { type: "image"; id: EntityId; parent: EntityId | null; geometry: Geometry; visibility: LayerVisibility; image: string } | { type: "artwork"; id: EntityId; parent: EntityId | null; geometry: Geometry; visibility: LayerVisibility; image: string };

export type LayerCommit = {
	revision: Revision,
	layer: EntityId,
};

export type LayerVisibility = {
	visible: boolean,
	opacity: number,
};

export type LmStudioConfig = {
	base_url?: string | null,
};

export type LocalConfig = Record<string, never>;

export type LoginEvent = { type: "progress"; message: string } | { type: "device_code"; verification_url: string; user_code: string };

export type Model = {
	provider: Provider,
	model: string | null,
	name: string,
	quantizations: Quantization[],
	vision: boolean,
};

export type ModelResources = {
	process_memory: number,
	system_memory: number,
	process_cpu: number,
	devices: DeviceResources[],
};

export type ModelSelection = {
	provider: Provider,
	model?: string | null,
	quantization?: string | null,
	vision: boolean,
};

export type OcrModel = { model: "paddleocr-vl-1.6" } | { model: "manga-ocr" } | { model: "baberu-ocr" };

export type OpenAiCompatibleConfig = {
	base_url?: string | null,
	vision?: boolean,
};

export type OpenAiConfig = Record<string, never>;

export type OpenRouterConfig = Record<string, never>;

export type Operation = { operation: "full" } | { operation: "through"; stage: Stage } | { operation: "only"; stage: Stage } | { operation: "stages"; stages: Stage[] };

export type Page = {
	id: EntityId,
	label: string,
	size: PageSize,
	layers: Layer[],
	regions: AnalysisRegion[],
};

export type PageImportSource = "files" | "folder";

export type PageSize = {
	width: number,
	height: number,
};

export type PageSummary = {
	id: EntityId,
	label: string,
	size: PageSize,
	source_asset: string | null,
	layer_count: number,
};

export type PaintBrush = {
	diameter: number,
	color: [number, number, number, number],
};

export type PipelineConfig = {
	detection: DetectionModel,
	ocr: OcrModel,
	translation: TranslationConfig,
	inpainting: InpaintingModel,
	/**
	 *  Settings for every model are kept independently of the active model.
	 *  The active stage fields above only select which profile is used.
	 */
	processor: ProcessorConfig,
};

export type Point = {
	x: number,
	y: number,
};

export type Preferences = {
	pipeline: PipelineConfig,
	providers: ProviderPreferences,
	typesetting: TypesettingConfig,
	languages: LanguageChoice[],
};

export type ProcessorConfig = {
	"koharu-layout-rfdetr-seg-2xl"?: KoharuLayoutRFDetrSeg2XLConfig | null,
	"flux2-klein"?: Flux2KleinConfig | null,
	"flux1-fill-dev"?: Flux1FillDevConfig | null,
	"rorem-mixed"?: RoremMixedConfig | null,
};

export type ProjectInfo = {
	name: string,
	revision: Revision,
	active_page: EntityId | null,
	can_undo: boolean,
	can_redo: boolean,
};

export type ProjectSummary = {
	name: string,
};

export type Provider = "local" | "atlas-cloud" | "openai" | "gemini" | "claude" | "deepseek" | "openai-compatible" | "openrouter" | "lm-studio" | "deepl" | "google-cloud-translation" | "caiyun";

export type ProviderConfig = { provider: "local"; settings: LocalConfig } | { provider: "atlas-cloud"; settings: AtlasCloudConfig } | { provider: "openai"; settings: OpenAiConfig } | { provider: "gemini"; settings: GeminiConfig } | { provider: "claude"; settings: ClaudeConfig } | { provider: "deepseek"; settings: DeepSeekConfig } | { provider: "openai-compatible"; settings: OpenAiCompatibleConfig } | { provider: "openrouter"; settings: OpenRouterConfig } | { provider: "lm-studio"; settings: LmStudioConfig } | { provider: "deepl"; settings: DeepLConfig } | { provider: "google-cloud-translation"; settings: GoogleCloudConfig } | { provider: "caiyun"; settings: CaiyunConfig };

export type ProviderPreference = {
	name: string,
	config: ProviderConfig,
	credential: CredentialInput | null,
};

export type ProviderPreferences = {
	entries: ProviderPreference[],
};

export type Quantization = {
	id: string,
	name: string,
};

export type RasterLayerKind = "cleanup" | "paint";

export type Reasoning = "low" | "medium" | "high" | "xhigh" | "max" | "ultra";

/**  Flat browser-to-desktop envelope: `{ id, command, payload }`. */
export type Request = {
	id: RequestId,
} & Command;

export type RequestId = string;

export type Revision = number;

export type RoremMixedConfig = {
	prompt?: string,
	negative_prompt?: string,
};

export type RunId = string;

export type Scope = { scope: "project" } | { scope: "pages"; value: EntityId[] } | { scope: "region"; value: {
	page: EntityId,
	bounds: Bounds,
} } | { scope: "entities"; value: EntityId[] };

export type ServerMessage = ServerMessage_Serialize | ServerMessage_Deserialize;

export type ServerMessage_Deserialize = ({ kind: "response"; id: RequestId; result: CommandResult | null; error: AppError | null }) & { event?: never; sequence?: never } | ({ kind: "event"; sequence: number; event: AppEvent }) & { error?: never; id?: never; result?: never };

export type ServerMessage_Serialize = ({ kind: "response"; id: RequestId; result?: CommandResult | null; error?: AppError | null }) & { event?: never; sequence?: never } | ({ kind: "event"; sequence: number; event: AppEvent }) & { error?: never; id?: never; result?: never };

export type SourceText = {
	text: string,
	language: string | null,
};

export type Stage = "detection" | "ocr" | "translation" | "inpainting";

export type StartupState = {
	preferences: Preferences,
	jobs: Job[],
	canvas: CanvasState,
};

export type TextAlignment = "Start" | "Center" | "End" | "Justify";

export type TextContent = {
	id: EntityId,
	source: SourceText | null,
	translation: Translation | null,
	role: string | null,
	source_region: EntityId | null,
};

export type TextLayoutKind = "point" | "paragraph";

export type TransformFrame = {
	element: EntityId,
	frame: Frame,
};

export type Translation = {
	text: string,
	language: string | null,
};

export type TranslationConfig = {
	model: ModelSelection,
	generation: GenerationConfig,
	target_language: string,
	instructions: string | null,
};

export type TypesettingConfig = {
	font_families?: string[],
};

export type Typography = {
	preferred_font: string | null,
	font_weight: number | null,
	font_style: FontStyle | null,
	size: number | null,
	auto_fit: boolean,
	color: [number, number, number, number] | null,
	stroke_color: [number, number, number, number] | null,
	stroke_width: number | null,
	alignment: TextAlignment | null,
	writing_mode: WritingMode | null,
};

export type TypographyUpdate = {
	layer: EntityId,
	typography: Typography,
};

export type UpdateInfo = {
	version: string,
	body: string | null,
};

export type UpdateProgress = {
	version: string,
	downloaded: number,
	total: number | null,
};

export type WindowState = {
	maximized: boolean,
	minimized: boolean,
	fullscreen: boolean,
	focused: boolean,
};

export type WritingMode = "Horizontal" | "Vertical";
