[package]
name = "koharu-updater"
version.workspace = true
edition.workspace = true
description = "Koharu's GitHub Releases updater."
license = "MIT OR Apache-2.0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
flate2 = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
serde_json = { workspace = true }
