[package]
name = "koharu-renderer"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
arc-swap = { workspace = true }
image = { workspace = true }
fast_image_resize = { workspace = true }
koharu-config = { workspace = true }
koharu-scene = { workspace = true }
koharu-runtime = { workspace = true }
skrifa = { workspace = true }
harfrust = { workspace = true }
hypher = { workspace = true }
icu_normalizer = { workspace = true }
icu_properties = { workspace = true, features = ["compiled_data"] }
icu_segmenter = { workspace = true, features = ["compiled_data"] }
jieba-rs = { workspace = true }
unicode-bidi = { workspace = true }
fontique = { workspace = true }
parking_lot = { workspace = true }
pollster = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
vello = { workspace = true }
webp = { workspace = true }
delaunator = "1.1.0"
nalgebra = "0.35.0"
cdt = "0.1.0"
nalgebra-sparse = "0.12.0"
spade = "2.15.1"

[dev-dependencies]
criterion = { workspace = true }
once_cell = { workspace = true }

[[bench]]
name = "rendering"
harness = false
