[package]
name = "koharu"
default-run = "koharu"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
console = { workspace = true }
dirs = { workspace = true }
koharu-app = { workspace = true }
koharu-canvas = { workspace = true }
koharu-desktop = { workspace = true }
koharu-pipeline = { workspace = true }
koharu-protocol = { workspace = true }
koharu-torch-sys = { workspace = true }
koharu-updater = { workspace = true }
parking_lot = { workspace = true }
open = { workspace = true }
rfd = { workspace = true }
serde_json = { workspace = true }
sentry = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[build-dependencies]
winresource = { workspace = true }
