name: Build

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: Swatinem/rust-cache@v2
      - uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.os, 'windows')
      - uses: actions/cache@v6
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - run: bun install
      - uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}/packages/koharu/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('packages/**/*.js', 'packages/**/*.jsx', 'packages/**/*.ts', 'packages/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-
      - run: bun tauri build --no-bundle
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: koharu-${{ matrix.os }}
          path: |
            target/release/koharu*
            target/release/koharu-torch.dll
            target/release/libkoharu-torch.so
            target/release/libkoharu-torch.dylib
          retention-days: 3
